info:
  contact:
    name: Matheus Abreu
  description: A Software for study goLang
  title: Red Dwarf
  version: "1.0"
paths:
  /health:
    get:
      description: Health cheack
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check if the service is running.
swagger: "2.0"
